# Generated by Django 4.0.1 on 2022-04-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blogpost_title', models.CharField(max_length=50)),
                ('Blogpost_blog', models.CharField(max_length=400)),
                ('Blogpost_date', models.DateField()),
            ],
        ),
    ]
