# Generated by Django 4.0.1 on 2022-04-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_remove_blogpost_blogpost_category4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='Blogpost_category2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='Blogpost_category3',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='Blogpost_desc',
            field=models.TextField(default='this is the description of blog', max_length=45),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='Blogpost_category1',
            field=models.CharField(choices=[('education', 'educational'), ('lifestyle', 'lifestyle'), ('sports', 'sports'), ('diy', 'diy'), ('fashion', 'fashion'), ('entertainment', 'entertainment'), ('science', 'science'), ('health', 'health'), ('personal', 'personal'), ('others', 'others')], default='others', max_length=50),
        ),
    ]
