# Generated by Django 4.0.1 on 2022-04-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_remove_blogpost_blogpost_category2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Blogpost_picture1',
            field=models.ImageField(default='blogapp/logo.png', upload_to='blogapp/images'),
        ),
    ]
