# Generated by Django 4.0.1 on 2022-04-18 18:32

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('blogapp', '0006_alter_blogpost_blogpost_picture1'),
    ]

    operations = [
        migrations.CreateModel(
            name='letsblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letsblog_title', models.CharField(max_length=40)),
                ('letsblog_desc', models.TextField(default='this is the description of blog', max_length=40)),
                ('letsblog_blog', models.TextField(max_length=700)),
                ('letsblog_category1', models.CharField(choices=[('education', 'educational'), ('lifestyle', 'lifestyle'), ('sports', 'sports'), ('diy', 'diy'), ('fashion', 'fashion'), ('entertainment', 'entertainment'), ('science', 'science'), ('health', 'health'), ('personal', 'personal'), ('others', 'others')], default='others', max_length=50)),
                ('letsblog_date', models.DateField()),
                ('letsblog_picture1', models.ImageField(upload_to='blogapp/images')),
                ('letsblog_tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
