# Generated by Django 4.0.1 on 2022-04-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_letsblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='id',
        ),
        migrations.RemoveField(
            model_name='letsblog',
            name='letsblog_tags',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='Blogpost_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
