# Generated by Django 4.0.1 on 2022-04-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_remove_blogpost_id_remove_letsblog_letsblog_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='Blogpost_id',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
