# Generated by Django 4.0.1 on 2022-04-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_remove_blogpost_blogpost_id_blogpost_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letsblog',
            name='id',
        ),
        migrations.AddField(
            model_name='letsblog',
            name='letsblog_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
