# Generated by Django 4.0.1 on 2022-04-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_blogpost_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Blogpost_blog',
            field=models.TextField(default='blog content test  <xyz>', max_length=400),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='Blogpost_title',
            field=models.CharField(default='title<xyz>', max_length=50),
        ),
    ]
