# Generated by Django 4.0.1 on 2022-04-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_alter_blogpost_blogpost_blog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='xxyyzz', max_length=100)),
                ('phonenum', models.IntegerField(default='9399237742')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('querry', models.CharField(default='no querry', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='Blogpost_blog',
            field=models.TextField(default='blog content test  <xyz>', max_length=5400),
        ),
    ]
